### ISSUE TITLE
Initializing of database table tx_ameosfilemanager_domain_model_folder fails

### ISSUE THREAD

**Issue by tobiasschaeferptb** [web-vision/typo3-ter-ameos_filemanager#2] opened 2016-10-24 14:57 UTC
Hello,

if the TYPO3 installation is located in a subdirectory of the webserver root directory the update script doesn't work because it determines the directory structure in a wrong way.
For example the fileadmin storage is set up with a relative path type and fileadmin/ as the path base .
/srv/www/htdocs/ is the webserver root directory
/srv/www/htdocs/cms/ is the TYPO3 root directory
/srv/www/htdocs/cms/fileadmin/ is where the fileadmin directory is located
The update script (class.ext_update.php) tries to determine the storage path in line 94:
$storagePath = $_SERVER['DOCUMENT_ROOT'] . '/' . $storage->getConfiguration()['basePath'];
$storagePath is /srv/www/htdocs//fileadmin/
Also note the additional but unnecessary slash.
Since there isn't a correct value /srv/www/htdocs/cms/ in the $_SERVER array I'm using $_SERVER['SCRIPT_FILENAME'] as a workaround:
$storagePath = str_replace('typo3/mod.php', '', $_SERVER['SCRIPT_FILENAME']) . $storage->getConfiguration()['basePath'];

Cheers, Tobias

**Comment by DanielSiepmann** [comment] 2016-10-24 15:00
Thanks @tobiasschaeferptb that should be an easy fix as TYPO3 already provides an API for that.

I'll try to come up with a fix during this week.
Are you able to try the fix and provide feedback so we can release a fixed version afterwards?

Thanks for the detailed error description.

**Comment by tobiasschaeferptb** [comment] 2016-10-24 15:09
Hello Daniel,

no problem. I will try the fix and will give you a feedback.
Thank you for the quick response.

Cheers, Tobias

**Comment by DanielSiepmann** [comment] 2016-10-28 10:25
Hey Tobias,

can you check whether Branch `hotfix/2-update` works for you?

You can download or clone it at https://github.com/web-vision/typo3-ter-ameos_filemanager/tree/hotfix/2-update

**Comment by borishinzer** [comment] 2016-10-28 10:25
Guten Tag,

vielen Dank für Ihre Nachricht. In der Zeit vom 25.10. - 28.10.2016 befinde ich mich auf der TYPO3 Konferenz und kann Ihre Emails nicht beantworten.

Bitte richten Sie Ihre Anfragen in der Zwischenzeit an: support@web-vision.de
In dringenden Fällen steht Ihnen Frau Petermann auch telefonisch zur Verfügung.

Vielen Dank für Ihr Verständnis.

Mit freundlichen Grüßen

Boris Hinzer

**Comment by tobiasschaeferptb** [comment] 2016-10-28 10:52
Hello Daniel,

using the constant PATH_site is working for me too.
I have 3 questions:
- at the end of the update script "?>" is missing. Is it by intention?
- since we have a lot of folder to scan by the update script it's taking longer than the max_execution_time defined within php.ini. Would it be an option for you to ini_set a higher max_execution_time in the update script? Possibly configurable with the extension manager, so it isn't needed to changed it globally within php.ini.
- it seems to be that the update script is scanning the folders only to a certain depth (4 subfolders). I couldn't find the corresponding code for this limitation.

Cheers, Tobias

**Comment by DanielSiepmann** [comment] 2016-10-28 12:00
Hey Tobias,
1. Was intended. You can find out more e.g. here: http://stackoverflow.com/a/4499749/1888377 
2. You can set it on your own, e.g. in `AdditionalConfiguration.php`. There is no need to adjust the extension. If the value doesn't fit for you, adjust it in your installation. Through `php.ini` or something else.
3. I can't find any code related to this. It will walk through all folders in any deep. Except recursion limit is reached. I currently don't have a working setup and can't test this. But it looks like the script has issues with the same name for folders in different places. Perhaps that might be an issue for you.

**Comment by DanielSiepmann** [comment] 2016-10-28 12:01
You might also take a look at https://typo3.org/extensions/repository/view/ameos_filemanager which should support TYPO3 till 7.x since January.

**Comment by tobiasschaeferptb** [comment] 2016-11-04 10:16
Hello Daniel,

I'm not sure about your last comment. I'm using the version 1.0.1 from the TER.
Regarding my 3rd question:
The problem wasn't cause by the update script, but by a missing configuration in Configuration/FlexForms/filemanager.xml
The Part for the startFolder doesn't have a maxLevels setting. So it seems to be that the tree-selector for the root filder (in the plugin) only renders 4 levels. I inserted a maxLevels of 10 and now it's showing the folders which were missing before:

```
                    <settings.startFolder>
                        <TCEforms>
                            <label>LLL:EXT:ameos_filemanager/Resources/Private/Language/locallang_be.xml:flexform.startFolder</label>
                            <config>
                                <type>select</type>
                                <foreign_table>tx_ameosfilemanager_domain_model_folder</foreign_table>
                                <size>30</size>
                                <minitems>1</minitems>
                                <maxitems>1</maxitems>
                                <renderMode>tree</renderMode>
                                <treeConfig>
                                    <expandAll>true</expandAll>
                                    <parentField>uid_parent</parentField>
                                    <appearance>
                                        <showHeader>true</showHeader>
                                        <!-- Added maxLevels -->
                                        <maxLevels>10</maxLevels>
                                    </appearance>
                                </treeConfig>
                            </config>
                        </TCEforms>
                    </settings.startFolder>
```

Additionally I modified the update script it didn't set the correct storageUid or identifier. It was always setting storage to 0 and identifier to NULL. It also had a double slash in the $storagePath variable, so I removed the slash behind PATH_site:

```
    function initializeDatabase() {
        $contenu = '';
        $this->objectManager = GeneralUtility::makeInstance('TYPO3\\CMS\\Extbase\\Object\\ObjectManager');
        $storageRepository = $this->objectManager->get('TYPO3\\CMS\\Core\\Resource\\StorageRepository');
        $storages = $storageRepository->findAll();
        $i=0;
        foreach ($storages as $storage) {
            $this->currentStorage = $storage;
            //$storagePath = PATH_site . '/' .  $storage->getConfiguration()['basePath'];
            $storagePath = PATH_site . $storage->getConfiguration()['basePath'];
            //$this->setDatabaseForFolder(substr($storagePath, 0,-1), $storagePath);
            $storageUid = $storage->getUid();
            $this->setDatabaseForFolder(substr($storagePath, 0,-1), $storagePath, $storageUid);
        }
        return LocalizationUtility::translate('initializeSuccess', 'ameos_filemanager');
    }
```

...

```
    //function setDatabaseForFolder($storageFolderPath, $folder, $uidParent = 0){
    function setDatabaseForFolder($storageFolderPath, $folder, $storageUid, $uidParent = 0){
        $this->countFolder ++;
        if ($handle = opendir($folder)) {
            while (false !== ($entry = readdir($handle))) {
                if ($entry != "." && $entry != "..") {
                    if(is_dir($folder . $entry)){
                        $res = $GLOBALS['TYPO3_DB']->exec_SELECTquery("uid", "tx_ameosfilemanager_domain_model_folder", "tx_ameosfilemanager_domain_model_folder.title like '". $entry ."'" );
                        $exist = false;
                        while ($row = $GLOBALS['TYPO3_DB']->sql_fetch_assoc($res)) {
                            if(Tools::getFolderPathFromUid($row['uid']) == str_replace($storageFolderPath,'',$folder . $entry))
                            {
                                $exist = true;
                                $uid = $row['uid'];
                                break;
                            }
                        }
                        if(!$exist)
                        {
                            $this->countAddedFolder ++;

                            $GLOBALS['TYPO3_DB']->exec_INSERTquery(
                                'tx_ameosfilemanager_domain_model_folder', 
                                array(
                                    'title' => $entry,
                                    'pid' => 0,
                                    'cruser_id' => $GLOBALS["BE_USER"]->user["uid"],
                                    'uid_parent' => $uidParent,
                                    // Added storage and identifier
                                    'storage' => $storageUid,
                                    'identifier' => $folder . $entry . '/',
                                    'crdate' => time(),
                                    'tstamp' => time(),
                                    'deleted' => 0,
                                    'hidden' => 0
                                )
                            );

                            $uid = $GLOBALS['TYPO3_DB']->sql_insert_id();
                            $this->countFolder++;

                        }
                        //$this->setDatabaseForFolder($storageFolderPath, $folder . $entry . '/', $uid);
                        $this->setDatabaseForFolder($storageFolderPath, $folder . $entry . '/', $storageUid, $uid);
                    }
                    else{
                        $this->setDatabaseForFile($storageFolderPath, $folder, $entry, $uidParent);
                    }
                }
            }
            closedir($handle);
        }
    }
```

Adding the path as the identifier may also solve the problem with the same name for folders in different places.

Cheers, Tobias

**Comment by DanielSiepmann** [comment] 2016-11-04 10:20
Perhaps you didn't notice that this Github Repository is not the official version of the extension as found inside the TER. As mentioned on Github, this is a fork as we needed to make the extension compatible.

The version here is 1.0.0 with our custom changes to make it as much compatible as we needed it for 6.2.

So if the issues are related to the official version, I recommend to contact pierre@ameos.com the author of the extension.

I think we will delete this repository in some weeks as the author provided a new version which should be compatible. So our fork won't lead to misunderstandings.

**Comment by tobiasschaeferptb** [comment] 2016-11-04 10:34
Hello Daniel,

thanks for the clarification. As you assumed I wasn't aware of the fact that this website isn't about the official version of ameos_filemanager. Since I couldn't find a bugtracker for the extension on forge.typo3.org I justed googled for "ameos_filemanager bugs" and your website was the first result.
I will contact Pierre Henrion.

Cheers, Tobias

**Comment by DanielSiepmann** [comment] 2016-11-04 10:36
Yes looks like they don't have anything configured in `ext_emconf.php` to show up on TER. Perhaps they don't even provide such things.

So I'll close the issue. If you still need some help from us, just comment again.

**Comment by DanielSiepmann** [comment] 2016-11-04 10:36
Yes looks like they don't have anything configured in `ext_emconf.php` to show up on TER. Perhaps they don't even provide such things.

So I'll close the issue. If you still need some help from us, just comment again.

**Closed as completed by DanielSiepmann** 2016-11-04 10:36 UTC
Labels: bug
